Repository ovh-ux/ovh-manager-web, pull requests merged in 2018-06, with the labels that each got.

#409 fix(incident): temporarily disable calls to ovh-tasks
  client/app/incident/incident.service.js
Labels: enhancement

#418 fix: chart now display correctly
  client/app/common/translations/Messages_fr_FR.xml
  client/app/private-database/metrics/private-database-metrics.constant.js
  client/app/private-database/metrics/private-database-metrics.controller.js
  client/app/private-database/metrics/private-database-metrics.html
  client/app/private-database/private-database.service.js
  client/app/resources/i18n/privateDatabase/Messages_fr_FR.xml
Labels: bug, quality check ok

#420 fix(cloudweb): use oui-tooltip in runtime
  client/app/hosting/runtimes/add/hosting-runtimes-add.html
  client/app/hosting/runtimes/edit/hosting-runtimes-edit.html
Labels: bug, quality check ok

#411 Feature/new navbar notification
  client/app/app.controller.js
  client/app/app.html
  client/app/app.js
  client/app/components/navbar/navbar-notification.service.js
  client/app/components/user/session.service.js
  client/app/resources/i18n/core/Messages_fr_FR.xml
Labels: feature, quality check ok

#415 fix(cloudweb): hide statistics in cloudweb dashboard
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
Labels: bug, quality check ok

#414 fix(cloudweb): reactivate MX plan menu button
  client/app/hosting/hosting-tabs.controller.js
Labels: feature, quality check ok

#419 fix(cloudweb): display runtimes in external multisite creation
  client/app/hosting/multisite/add/external/hosting-multisite-add-external.html
Labels: bug, quality check ok

#416 Track/update : update tracking in web manager
  client/app/components/expiration/service-expiration-date.component.html
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/domain/anycast/domain-dns-anycast.controller.js
  client/app/domain/dns/DNS.html
  client/app/domain/domain.html
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
  client/app/domain/subdomain/add/domain-subdomain-add.controller.js
  client/app/domain/webhosting-enable/domain-enable-web-hosting.controller.js
  client/app/email-domain/order/email-domain-order.controller.js
  client/app/hosting/change-main-domain/hosting-change-main-domain.controller.js
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/hosting.html
  client/app/hosting/multisite/order/hosting-multisite-order.controller.js
  client/app/hosting/offer/upgrade/hosting-offer-upgrade.controller.js
  client/app/private-database/order/sql-database-order-controller.js
Labels: enhancement, quality check ok

#426 fix(translations): fix translations path
  client/app/components/ovh-angular-actions-menu/ovh-angular-actions-menu.module.js
Labels: bug

#412 fix(cloudweb): fix "sqlLocal" text
  client/app/resources/i18n/hosting/Messages_fr_FR.xml
Labels: bug, quality check ok

#417 feat(cloudweb): display default runtime in general informations tab
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.controller.js
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/runtimes/hosting-runtimes.service.js
  client/app/resources/i18n/hosting/Messages_fr_FR.xml
Labels: feature, quality check ok

#430 hotfix(hosting): send the right option when switching offer
  client/app/hosting/offer/upgrade/hosting-offer-upgrade.html
Labels: bug, quality check ok

#434 hotfix(*): remove "track by $index" on ng-options
  client/app/hosting/database/private-activation/database-private-activation.html
  client/app/hosting/runtimes/add/hosting-runtimes-add.html
  client/app/hosting/runtimes/edit/hosting-runtimes-edit.html
Labels: bug, quality check ok

#442 fix(hosting): fix cloudweb offer name
  client/app/resources/i18n/hosting/Messages_fr_FR.xml
Labels: bug, quality check ok

#444 fix(cloudweb): deactivate email shortcut
  client/app/hosting/hosting-tabs.controller.js
Labels: bug, quality check

#450 fix(package engines): require node 8 current lts
  package-lock.json
  package.json
Labels: bug, enhancement

#433 Feat/add cloudweb in order menu
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/resources/i18n/core/Messages_fr_FR.xml
  constants.config.js
Labels: feature, quality check ok

#435 fix: fix guide tile
  client/app/components/guides/guides.html
  client/app/components/guides/guides.less
Labels: bug, quality check ok

#413 fix(cloudweb): display configuration usage in disk usage
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/hosting.constant.js
  client/app/hosting/hosting.service.js
  client/app/resources/i18n/hosting/Messages_fr_FR.xml
Labels: bug, quality check ok
