Repository ovh-ux/ovh-manager-web, pull requests merged in 2018-08, with the labels that each got.

#485 fix(deps): raven-js ENORESTARGET
  bower.json
Labels: bug

#484 fix(hosting.private-database.order): retrieve dbPack for startSQL order
  client/app/private-database/order/sql-database-order-controller.js
Labels: bug, quality check ok

#489 chore(deps): Revert "fix(deps): raven-js ENORESTARGET"
  bower.json
Labels: bug

#496 fix(hosting.tabs): add icon for external redirection
  client/app/components/tabs/tabs.html
Labels: bug, quality check ok

#497 fix(domain.dnsserver): add-icon-external-link
  client/app/domain/dns/DNS.html
  client/app/resources/i18n/domain/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#502 fix(constants): new signup url
  constants.config.js
Labels: enhancement

#507 style(webhosting.automated-email): change class label
  client/app/hosting/automated-emails/AUTOMATED_EMAILS.html
Labels: enhancement

#505 style(webhosting.dashboard): change class label
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/hosting.controller.js
Labels: enhancement

#506 fix(cloudweb): display default runtime in general infos
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.controller.js
  client/app/hosting/runtimes/hosting-runtimes.service.js
Labels: bug, quality check ok

#509 refactor(hosting.automated.email): use oui-button
  client/app/hosting/automated-emails/AUTOMATED_EMAILS.html
Labels: enhancement

#511 fix(emails): email details list
  client/app/email-domain/delegate/email-domain-delegate.controller.js
Labels: bug, quality check ok

#519 fix(hosting): call ovhConfigRefresh when last call was at least 12h ago
  client/app/hosting/hosting.controller.js
Labels: enhancement, quality check ok

#517 fix(create-auto-response): start date fix
  client/app/email-domain/email/responder/create/email-domain-email-responder-create.html
Labels: bug, quality check ok
