Repository ovh-ux/ovh-manager-web, pull requests merged in 2018-10, with the labels that each got.

#579 fix(deps): bump ovh-module-exchange to v8.0.8
  yarn.lock
Labels: bug, quality check ok

#580 style(domain.bulk.action): use oui-component
  client/app/domains/domains.html
  client/app/domains/domains.popover.html
Labels: enhancement

#583 Feat/banner current summit
  client/app/configuration/configuration.controller.js
  client/app/configuration/configuration.html
  client/app/core/translations/Messages_fr_FR.xml
  client/assets/images/summit/2017-banner-en.png
  client/assets/images/summit/2017-banner-fr.png
  client/assets/images/summit/banner-manager-2500x235-en.jpg
  client/assets/images/summit/banner-manager-2500x235-fr.jpg
  client/assets/images/summit/banner-manager-768x200-en.jpg
  client/assets/images/summit/banner-manager-768x200-fr.jpg
Labels: feature, quality check

#586 fix(email): removed useless repeated id
  client/app/email-domain/email/account/create/email-domain-email-account-create.html
Labels: bug

#576 style(private.database.state): move progress bar in tile
  client/app/private-database/state/private-database-state.html
Labels: enhancement

#594 Fix/perf
  client/app/app.js
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/components/user/session.controller.js
  client/app/css/less/common/navbar.less
  client/app/index.html
  package.json
  yarn.lock
Labels: enhancement

#595 build: remove deprecated npm-scripts-config|conventional-changelog
  .scriptsrc
  package.json
  yarn.lock
Labels: enhancement

#599 fix: update gitignore file
  .gitignore
Labels: enhancement

#593 fix(banner): display only for some subsidiaries
  client/app/configuration/configuration.controller.js
  client/app/configuration/configuration.html
Labels: bug, quality check

#604 fix: remove border top of the summit banner
  client/app/css/less/common/navbar.less
Labels: bug

#609 refactor(database.dumps): use oui-back-button
  client/app/hosting/database/dump/DUMPS.html
Labels: enhancement

#608 fix(domain.operation.update): text not interpreted unnecessary
  client/app/domain-operation/update/domain-operation-update.html
Labels: bug

#607 refactor(domain.operation): use oui-action-menu
  client/app/domain-operation/domain-operation.html
  client/app/domain-operation/domain-operation.popover.html
Labels: enhancement

#610 refactor(hosting.task): use class oui-status
  client/app/hosting/task/TASK.html
Labels: enhancement

#612 refactor(hosting.general.informations.ssl): use oui-action-menu
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
Labels: enhancement

#611 build: add clean script
  package.json
Labels: enhancement

#613 fix(private.database.state): dont display menu when expired
  client/app/private-database/state/private-database-state.html
Labels: bug

#615 build: remove duplicate dependencies
  client/app/css/less/common/countryIcon.less
  client/app/css/less/common/distributionIcon.less
  client/app/css/less/common/icon.less
  client/app/css/less/common/navbar.less
  package.json
  yarn.lock
Labels: enhancement

#619 fix(domain.tasks): display oui-status correctly
  client/app/domain/tasks/TASKS.html
Labels: bug

#620 refactor(private.database): use oui-back-button
  client/app/private-database/database/archive/dump/private-database-database-archive-dump.html
  client/app/private-database/database/archive/list/private-database-database-archive-list.html
  client/app/private-database/database/dump/private-database-database-dump.html
  client/app/private-database/database/extension/private-database-database-extension.html
  client/app/private-database/database/user/private-database-database-user.html
  client/app/private-database/user/grants/private-database-user-grants.html
Labels: enhancement

#614 refactor(domain.dnssec): use oui-action-menu
  client/app/domain/dnssec/DNSSEC.html
Labels: enhancement

#621 refactor(private.database.archive.list): use class oui-status
  client/app/private-database/database/archive/list/private-database-database-archive-list.html
Labels: enhancement

#623 refactor(email.domain.task): use oui-status class
  client/app/email-domain/task/email-domain-task.html
Labels: enhancement

#626 fix(ie11): app will now display correctly
  client/app/app.js
  client/app/config/constants.config.js
  client/app/index.js
  package.json
  yarn.lock
Labels: bug

#625 build(changelog): use npx conventional-changelog-cli with angular preset
  package.json
  yarn.lock
Labels: enhancement

#622 refactor(email.domain.general.informations): use oui-component
  client/app/components/guides/guides.html
  client/app/email-domain/general-informations/email-domain-general-informations.html
Labels: enhancement

#631 refactor(email.domain.mailing.list.view): use oui-action-menu
  client/app/email-domain/mailing-list/email-domain-mailing-list-view.html
  client/app/email-domain/mailing-list/email-domain-mailing-list.popover.html
Labels: enhancement

#632 refactor(email.domain.mailing.list): use oui-back-button
  client/app/email-domain/mailing-list/moderators/email-domain-mailing-list-moderators-view.html
  client/app/email-domain/mailing-list/subscribers/email-domain-mailing-list-subscribers-view.html
Labels: enhancement

#588 fix(domain): allow subnet in IPs
  client/app/domain/domain-validator.service.js
Labels: bug, quality check ok

#633 refactor(email.domain.filter): use oui-status class
  client/app/email-domain/delegate/filter/email-domain-delegate-filter.html
  client/app/email-domain/email/filter/email-domain-email-filter.html
Labels: enhancement

#634 refactor(email.domain.delegate): use oui-back-button
  client/app/email-domain/delegate/filter/email-domain-delegate-filter.html
  client/app/email-domain/delegate/responder/email-domain-delegate-responder.html
Labels: enhancement

#635 refactor(email.domain.delegate.responder): use oui-component
  client/app/email-domain/delegate/responder/email-domain-delegate-responder.html
  client/app/email-domain/delegate/responder/email-domain-delegate-responder.popover.html
Labels: enhancement

#552 refactor(hosting.cron): use oui-action-menu
  client/app/hosting/cron/CRON.html
  client/app/hosting/translations/Messages_fr_FR.xml
Labels: enhancement, translation required

#629 refactor(email.domain.email.account): use oui-component
  client/app/email-domain/delegate/account/email-domain-delegate-account.html
  client/app/email-domain/delegate/email-domain-delegate.popover.html
  client/app/email-domain/email-domain.popover.html
  client/app/email-domain/email/account/email-domain-email-account.html
  client/app/email/translations/Messages_fr_FR.xml
Labels: enhancement, translation required

#562 refactor(private.database.state): use oui-action-menu2
  client/app/private-database/state/private-database-state.html
  client/app/private-database/translations/Messages_fr_FR.xml
Labels: enhancement, translation required

#640 build(commitlint): remove unused config-conventional
  .commitlintrc.js
  package.json
  yarn.lock
Labels: enhancement

#641 refactor(deps): remove unused ovh-angular-doubleauth-backupcode module
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement

#643 Upgrade Emailpro and Exchange modules
  yarn.lock
Labels: enhancement

#624 chore(order): add texts under each db type
  client/app/css/less/common/tooltip.less
  client/app/private-database/order/sql-database-order.html
  client/app/private-database/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#516 fix(domain): return update owner url if whoisOwner.id is defined
  client/app/domain/domain-tabs.controller.js
  client/app/domain/domain.constant.js
  client/app/domain/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#650 fix(privatedb.order): warn when a free offer is still available
  client/app/private-database/order/sql-database-order-controller.js
  client/app/private-database/order/sql-database-order.html
  client/app/private-database/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#660 Feat/summit banner : change subscription banner to live banner
  client/app/configuration/configuration.html
  client/app/core/translations/Messages_cs_CZ.xml
  client/app/core/translations/Messages_de_DE.xml
  client/app/core/translations/Messages_en_ASIA.xml
  client/app/core/translations/Messages_en_AU.xml
  client/app/core/translations/Messages_en_CA.xml
  client/app/core/translations/Messages_en_GB.xml
  client/app/core/translations/Messages_en_SG.xml
  client/app/core/translations/Messages_en_US.xml
  client/app/core/translations/Messages_es_ES.xml
  client/app/core/translations/Messages_es_US.xml
  client/app/core/translations/Messages_fi_FI.xml
  client/app/core/translations/Messages_fr_CA.xml
  client/app/core/translations/Messages_fr_FR.xml
  client/app/core/translations/Messages_it_IT.xml
  client/app/core/translations/Messages_lt_LT.xml
  client/app/core/translations/Messages_nl_NL.xml
  client/app/core/translations/Messages_pl_PL.xml
  client/app/core/translations/Messages_pt_PT.xml
  client/assets/images/summit/banner-manager-2500x235-en.jpg
  client/assets/images/summit/banner-manager-2500x235-fr.jpg
  client/assets/images/summit/banner-manager-768x200-en.jpg
  client/assets/images/summit/banner-manager-768x200-fr.jpg
Labels: quality check ok

#661 fix(domain.redirection): allow * subdomain
  client/app/domain/redirection/add/domain-redirection-add.controller.js
Labels: enhancement, quality check ok

#663 fix(privateDb.order): display warning for preselected hosting
  client/app/private-database/order/sql-database-order-controller.js
Labels: bug, quality check ok

#668 fix(privatedb.order): display warning for 512MB only
  client/app/private-database/order/sql-database-order-controller.js
  client/app/private-database/order/sql-database-order.html
Labels: bug, quality check ok

#671 fix(hosting.multisite): remove bug in code
  client/app/hosting/multisite/hosting-multisite.controller.js
Labels: bug, quality check ok

#676 refactor: remove summit banner
  client/app/configuration/configuration.controller.js
  client/app/configuration/configuration.html
  client/app/core/translations/Messages_cs_CZ.xml
  client/app/core/translations/Messages_de_DE.xml
  client/app/core/translations/Messages_en_ASIA.xml
  client/app/core/translations/Messages_en_AU.xml
  client/app/core/translations/Messages_en_CA.xml
  client/app/core/translations/Messages_en_GB.xml
  client/app/core/translations/Messages_en_SG.xml
  client/app/core/translations/Messages_en_US.xml
  client/app/core/translations/Messages_es_ES.xml
  client/app/core/translations/Messages_es_US.xml
  client/app/core/translations/Messages_fi_FI.xml
  client/app/core/translations/Messages_fr_CA.xml
  client/app/core/translations/Messages_fr_FR.xml
  client/app/core/translations/Messages_it_IT.xml
  client/app/core/translations/Messages_lt_LT.xml
  client/app/core/translations/Messages_nl_NL.xml
  client/app/core/translations/Messages_pl_PL.xml
  client/app/core/translations/Messages_pt_PT.xml
  client/assets/images/summit/banner-manager-2500x235-en.jpg
  client/assets/images/summit/banner-manager-2500x235-fr.jpg
  client/assets/images/summit/banner-manager-768x200-en.jpg
  client/assets/images/summit/banner-manager-768x200-fr.jpg
Labels: enhancement, quality check ok

#683 build(scripts): add clean dist script
  package.json
Labels: enhancement

#681 refactor(eslint): switch to json format as configuration file
  .eslintrc.json
Labels: enhancement

#682 refactor: extract configuration from package.json into json files
  .huskyrc.json
  .lintstagedrc.json
  package.json
Labels: enhancement

#684 refactor(domain.dynhost.login): use oui-action-menu
  client/app/domain/dynhost/login/domain-dynhost-login.html
  client/app/domain/dynhost/login/domain-dynhost-login.popover.html
Labels: enhancement

#685 build(deps): upgrade manager-webpack-config to v2.3.4
  yarn.lock
Labels: enhancement

#679 fix(domain.general.informations): tooltip flashing
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
Labels: bug

#675 fix(email.rules): handle rules with special names
  client/app/email-domain/email-domain.service.js
  client/app/email-domain/email/filter/create/email-domain-email-filter-create.html
  client/app/email-domain/email/filter/edit/email-domain-email-filter-edit.html
Labels: bug, quality check ok

#690 Bump manager webpack config
  README.md
  yarn.lock
Labels: enhancement

#692 fix: remove sk_SK from language constants
  client/app/app.js
  client/app/config/constants.config.js
  client/app/core/translations/Messages_sk_SK.xml
  client/app/domain/translations/Messages_sk_SK.xml
  client/app/domains/translations/Messages_sk_SK.xml
  client/app/hosting/translations/Messages_sk_SK.xml
Labels: bug

#695 style(package.json): sort entries
  package.json
Labels: enhancement

#697 refactor(components): add webUniverseComponents module
  client/app/app.js
  client/app/webUniverseComponents/index.js
Labels: :jack_o_lantern: one-manager

#701 build(components.availableips): remove unused module
  client/app/components/availableIp/availableIp.js
Labels: :jack_o_lantern: one-manager

#704 build(webpack): set correct entry list
  webpack.config.js
Labels: :jack_o_lantern: one-manager

#705 fix(deps): import everything related to angular-translate
  client/app/index.js
  package.json
  yarn.lock
Labels: :jack_o_lantern: one-manager

#707 refactor: use @ovh-ux/translate-async-loader
  client/app/app.js
  client/app/async-loader.factory.js
  package.json
  yarn.lock
Labels: :jack_o_lantern: one-manager

#703 refactor(components.checkboxswitch): remove unused component
  client/app/components/checkboxSwitch/checkboxSwitch-2.css
  client/app/components/checkboxSwitch/checkboxSwitch.css
  client/app/components/checkboxSwitch/checkboxSwitch.js
Labels: :jack_o_lantern: one-manager, quality check

#706 refactor(components.converter): move to webUniverseComponents
  client/app/components/converter/converter.service.js
  client/app/hosting/database/hosting-database.controller.js
  client/app/hosting/hosting.controller.js
  client/app/hosting/hosting.service.js
  client/app/private-database/order/sql-database-order-controller.js
  client/app/private-database/state/private-database-state.controller.js
  client/app/webUniverseComponents/converter/converter.service.js
  client/app/webUniverseComponents/converter/index.js
  client/app/webUniverseComponents/index.js
Labels: :jack_o_lantern: one-manager, quality check ok

#708 refactor(components.cron*): move to webUniverseComponents
  client/app/components/cron/cronEditor.controller.js
  client/app/components/cron/cronEditor.directive.js
  client/app/components/cron/cronExpertHelp.directive.js
  client/app/components/cron/cronExpertHelp.html
  client/app/components/cron/cronSimpleSummary.controller.js
  client/app/components/cron/cronSimpleSummary.directive.js
  client/app/components/cron/cronSimpleSummary.html
  client/app/hosting/cron/add-or-edit/hosting-cron-add-or-edit.controller.js
  client/app/hosting/cron/add-or-edit/hosting-cron-add-or-edit.html
  client/app/hosting/translations/Messages_fr_FR.xml
  client/app/webUniverseComponents/cron-validator/cron-validator.js
  client/app/webUniverseComponents/cron-validator/index.js
  client/app/webUniverseComponents/cron/cronEdit.html
  client/app/webUniverseComponents/cron/cronEditor.controller.js
  client/app/webUniverseComponents/cron/cronEditor.directive.js
  client/app/webUniverseComponents/cron/cronExpert.html
  client/app/webUniverseComponents/cron/cronExpertHelp.directive.js
  client/app/webUniverseComponents/cron/cronExpertHelp.html
  client/app/webUniverseComponents/cron/cronSimple.html
  client/app/webUniverseComponents/cron/cronSimpleSummary.controller.js
  client/app/webUniverseComponents/cron/cronSimpleSummary.directive.js
  client/app/webUniverseComponents/cron/cronSimpleSummary.html
  client/app/webUniverseComponents/cron/index.js
  client/app/webUniverseComponents/cron/translations/Messages_fr_FR.xml
  client/app/webUniverseComponents/index.js
Labels: :jack_o_lantern: one-manager, quality check ok, translation required

#710 build(deps): upgrade manager-webpack-config to v2.4.0
  package.json
  yarn.lock
Labels: :jack_o_lantern: one-manager

#709 refactor(components.dnszonevalidator): move directive to dns-zone
  client/app/components/dnsZoneValidator/dnsZoneValidator.directive.js
  client/app/dns-zone/new/dnsZoneValidator.directive.js
Labels: :jack_o_lantern: one-manager, quality check ok

#711 refactor(components.documentupload): remove unused component
  client/app/components/document-upload/document-upload.controller.js
Labels: :jack_o_lantern: one-manager, enhancement

#713 refactor(components.upload): remove unused component
  client/app/components/upload/upload.controller.js
  client/app/components/upload/upload.html
  client/app/components/upload/upload.js
Labels: :jack_o_lantern: one-manager, enhancement

#712 refactor(components.v6uiswitch): remove unused component
  client/app/components/v6UiSwitch/v6UiSwitch.directive.js
Labels: :jack_o_lantern: one-manager, enhancement
