Repository ovh-ux/ovh-manager-web, pull requests merged in 2018-09, with the labels that each got.

#524 refactor(domain.dynhost): use oui-action-menu
  client/app/domain/dynhost/domain-dynhost.html
  client/app/domain/dynhost/domain-dynhost.popover.html
Labels: enhancement

#522 refactor(domain.zone): use oui-action-menu
  client/app/domain/zone/ZONE.html
  client/app/domain/zone/domain-zone-dns.popover.html
Labels: enhancement

#525 refactor(domain.dynhost.login): use oui-back-button
  client/app/domain/dynhost/login/domain-dynhost-login.html
Labels: enhancement, quality check

#523 refactor(domain.redirection): use oui-action-menu
  client/app/domain/redirection/REDIRECTION.html
  client/app/domain/redirection/domain-redirection.popover.html
Labels: enhancement

#533 fix(menu): sort domains by name
  client/app/components/sidebar-menu/sidebar-menu.config.js
  package-lock.json
Labels: enhancement, quality check ok

#537 fix(domain): No alert if hosting is not attached
  client/app/domain/general-informations/domain-general-informations.controller.js
  client/app/email-domain/email/responder/email-domain-email-responder.controller.js
  client/app/hosting/multisite/hosting-multisite.service.js
Labels: enhancement, quality check

#508 Feat/ Local SEO
  bower.json
  client/app/email-domain/email/responder/email-domain-email-responder.controller.js
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.controller.js
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/hosting-tabs.controller.js
  client/app/hosting/local-seo/LOCAL_SEO.html
  client/app/hosting/local-seo/delete/hosting-local-seo-delete.controller.js
  client/app/hosting/local-seo/delete/hosting-local-seo-delete.html
  client/app/hosting/local-seo/hosting-local-seo.controller.js
  client/app/hosting/local-seo/hosting-local-seo.service.js
  client/app/hosting/runtimes/hosting-runtimes.service.js
  client/app/resources/i18n/core/Messages_fr_FR.xml
  client/app/resources/i18n/hosting/Messages_fr_FR.xml
  constants.config.js
Labels: feature, quality check ok, translation required

#540 fix(email): fix migration doc links for poland
  client/app/email-domain/email/account/migrate/email-domain-email-account-migrate.controller.js
  constants.config.js
Labels: bug, quality check ok

#535 refactor(hosting.ftp): use oui-action-menu
  client/app/hosting/ftp/FTP.html
  client/app/hosting/popover/multiftp.html
Labels: enhancement

#545 fix(localseo): disable feature for other subs than FR
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.controller.js
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/hosting-tabs.controller.js
Labels: bug, quality check ok

#551 refactor(hosting.runtimes): use class oui-status
  client/app/hosting/runtimes/RUNTIMES.html
Labels: enhancement

#550 refactor(hosting.general.informations): use ovh-oui-kit local seo option
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
Labels: enhancement, quality check ok

#549 refactor(hosting.database): use oui-action-menu
  client/app/hosting/database/DATABASE_LIST.html
Labels: enhancement, quality check

#557 refactor(hosting.envvars): use class oui-status
  client/app/hosting/envvars/ENVVARS.html
Labels: enhancement

#560 refactor(private.databse.state): use oui-status & class
  client/app/private-database/state/private-database-state.html
Labels: enhancement

#558 fix: cron job edit
  client/app/hosting/cron/hosting-cron.service.js
Labels: bug, quality check ok

#563 Fix/private database oomkill warn
  .gitignore
  client/app/common/translations/Messages_cs_CZ.json
  client/app/common/translations/Messages_es_US.json
  client/app/common/translations/Messages_nl_NL.json
  client/app/common/translations/Messages_pl_PL.json
  client/app/private-database/state/private-database-state.html
  package-lock.json
Labels: enhancement, quality check ok

#564 refactor(private.database.list): use oui-component
  client/app/private-database/database/list/popover/list.html
  client/app/private-database/database/list/private-database-database-list.html
Labels: enhancement

#561 refactor(private.databse.state): use oui-action-menu
  client/app/private-database/state/private-database-state.html
Labels: enhancement

#565 style(hosting.general.informations): move progress bar in tile
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
Labels: enhancement

#573 chore(*): remove useless files
  client/app/email/translations/desktop.ini
  client/app/mailing-list/translations/desktop.ini
  client/app/mx-plan/translations/desktop.ini
Labels: enhancement

#408 chore(*): replace bower with yarn
  .bowerrc
  .editorconfig
  .gitignore
  .npmrc
  Assets.js
  Gruntfile.js
  Makefile
  bower.json
  client/app/common/translations/Messages_de_DE.json
  client/app/common/translations/Messages_en_AU.json
  client/app/common/translations/Messages_en_CA.json
  client/app/common/translations/Messages_en_GB.json
  client/app/common/translations/Messages_en_SG.json
  client/app/common/translations/Messages_en_US.json
  client/app/common/translations/Messages_es_ES.json
  client/app/common/translations/Messages_fi_FI.json
  client/app/common/translations/Messages_fr_CA.json
  client/app/common/translations/Messages_fr_FR.json
  client/app/common/translations/Messages_it_IT.json
  client/app/common/translations/Messages_lt_LT.json
  client/app/common/translations/Messages_pt_PT.json
  client/app/components/ovh-angular-actions-menu/ovh-angular-actions-menu.module.js
  client/app/components/ovh-angular-sidebar-menu/ovh-angular-sidebar-menu.module.js
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/components/sidebar-menu/sidebar-menu.less
  client/app/components/user/session.service.js
  client/app/css/source.less
  client/app/css/source.scss
  client/app/index.ejs
  package-lock.json
  package.json
  server/config/express.js
  yarn.lock
Labels: enhancement, quality check ok

#577 fix(app): restores OTRS translations
  Gruntfile.js
  client/app/app.js
Labels: bug, quality check
