Repository ovh-ux/ovh-manager-web, pull requests merged in 2018-04, with the labels that each got.

#378 fix(domain.dns): allow to reset DNS servers when DNS are not managed by OVH
  client/app/domain/dns/DNS.html
  client/app/domain/dns/domain-dns.controller.js
Labels: bug, quality check ok

#366 Chore/privatedb update database minimum length
  client/app/private-database/database/add/private-database-database-add.controller.js
Labels: enhancement, quality check ok

#356 Fix/domain redirection edit error
  client/app/domain/redirection/domain-redirection.controller.js
  client/app/domain/redirection/edit/domain-redirection-edit.controller.js
Labels: bug, quality check ok

#379 chore(gruntfile): remove open task
  Gruntfile.js
  package-lock.json
  package.json
  server/app.js
Labels: enhancement

#336 Fix/db grant multiple requests
  client/app/private-database/user/grants/private-database-user-grants.controller.js
Labels: bug, quality check ok

#383 apply the same fix as in dedicated to fix dev authentication
  server/routes.js
Labels: bug

#380 chore: git push on post-version
  package.json
Labels: bug

#382 Fix CKEditor modals
  client/app/app.controller.js
Labels: bug, quality check ok

#377 fix(*): rename services to v6 and v7
  Gruntfile.js
  bower.json
  client/app/app.js
  client/app/components/user/session.service.js
  client/app/index.ejs
  constants.config.js
  package-lock.json
Labels: enhancement, quality check ok

#388 Feature/db configuration oui kit
  client/app/private-database/configuration/private-database-configuration.controller.js
  client/app/private-database/configuration/private-database-configuration.html
  client/app/resources/i18n/privateDatabase/Messages_fr_FR.xml
Labels: quality check ok, translation required

#390 chore(gruntfile): remove unused checkUrlsInConstants task
  Gruntfile.js
  package-lock.json
  package.json
Labels: enhancement
