Repository ovh-ux/ovh-manager-web, pull requests merged in 2018-07, with the labels that each got.

#456 Chore/guides link
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/multisite/MULTISITE.html
  client/app/resources/i18n/core/Messages_fr_FR.xml
  constants.config.js
Labels: enhancement, quality check

#448 feat(navbar): add notifications placeholder translations
  client/app/app.js
  client/app/components/navbar/navbar-notification.service.js
  client/app/resources/i18n/core/Messages_fr_FR.xml
Labels: feature, quality check ok

#460 fix(email): add subcribers in series instead of parallel
  client/app/email-domain/mailing-list/email-domain-mailing-list.service.js
  client/app/email-domain/mailing-list/subscriber/delete/email-domain-mailing-list-subscriber-delete.controller.js
  client/app/email-domain/mailing-list/subscribers/create/email-domain-mailing-list-subscribers-create.controller.js
  client/app/email-domain/mailing-list/subscribers/delete/email-domain-mailing-list-subscribers-delete.controller.js
Labels: bug

#464 fix(email-domain migrate): use heading attribut on oui-back-button
  bower.json
  client/app/email-domain/email/account/migrate/email-domain-email-account-migrate.html
  package-lock.json
Labels: enhancement

#466 fix(hosting): fix cloudweb configuration quota
  client/app/hosting/hosting.constant.js
Labels: bug, quality check ok

#468 fix(*): order account link redirects to wront page
  client/app/email-domain/email/account/migrate/email-domain-email-account-migrate.html
Labels: bug, quality check ok

#467 fix(hosting): update password conditions in hosting module creation
  client/app/hosting/module/add/hosting-module-add.controller.js
  client/app/hosting/module/add/hosting-module-add.html
  client/app/hosting/module/hosting-module.constant.js
Labels: bug, quality check ok

#476 fix(domain.zone): fix dns NAPTR and SRV record creation
  client/app/domain/domain-validator.service.js
  client/app/domain/zone/record/SRV/domain-zone-record-SRV.html
Labels: bug, quality check ok

#479 chore(deps): bump ovh-ui-kit and ovh-ui-kit-bs
  bower.json
  package-lock.json
Labels: enhancement, ovh-ui-kit

#469 Feature: email manage responders
  client/app/email-domain/email-domain.service.js
  client/app/email-domain/email/responder/email-domain-email-responder.controller.js
  client/app/email-domain/email/responder/email-domain-email-responder.html
  client/app/email-domain/email/responder/email-domain-email-responder.popover.html
Labels: bug, quality check ok
