Repository ovh-ux/ovh-manager-web, pull requests merged in 2018-12, with the labels that each got.

#808 Submit and retrieve translations
  client/app/core/translations/Messages_pl_PL.xml
  client/app/domain/translations/Messages_de_DE.xml
  client/app/hosting/translations/Messages_cs_CZ.xml
  client/app/hosting/translations/Messages_de_DE.xml
  client/app/hosting/translations/Messages_en_ASIA.xml
  client/app/hosting/translations/Messages_en_AU.xml
  client/app/hosting/translations/Messages_en_CA.xml
  client/app/hosting/translations/Messages_en_GB.xml
  client/app/hosting/translations/Messages_en_SG.xml
  client/app/hosting/translations/Messages_en_US.xml
  client/app/hosting/translations/Messages_es_ES.xml
  client/app/hosting/translations/Messages_es_US.xml
  client/app/hosting/translations/Messages_fi_FI.xml
  client/app/hosting/translations/Messages_fr_CA.xml
  client/app/hosting/translations/Messages_it_IT.xml
  client/app/hosting/translations/Messages_lt_LT.xml
  client/app/hosting/translations/Messages_nl_NL.xml
  client/app/hosting/translations/Messages_pl_PL.xml
  client/app/hosting/translations/Messages_pt_PT.xml
  client/app/private-database/translations/Messages_cs_CZ.xml
  client/app/private-database/translations/Messages_de_DE.xml
  client/app/private-database/translations/Messages_en_ASIA.xml
  client/app/private-database/translations/Messages_en_AU.xml
  client/app/private-database/translations/Messages_en_CA.xml
  client/app/private-database/translations/Messages_en_GB.xml
  client/app/private-database/translations/Messages_en_SG.xml
  client/app/private-database/translations/Messages_en_US.xml
  client/app/private-database/translations/Messages_es_ES.xml
  client/app/private-database/translations/Messages_es_US.xml
  client/app/private-database/translations/Messages_fi_FI.xml
  client/app/private-database/translations/Messages_fr_CA.xml
  client/app/private-database/translations/Messages_fr_FR.xml
  client/app/private-database/translations/Messages_it_IT.xml
  client/app/private-database/translations/Messages_lt_LT.xml
  client/app/private-database/translations/Messages_nl_NL.xml
  client/app/private-database/translations/Messages_pl_PL.xml
  client/app/private-database/translations/Messages_pt_PT.xml
Labels: bug

#815 fix(deps): upgrade ovh-module-exchange to v9.2.0
  package.json
  yarn.lock
Labels: bug

#807 fix(hosting): avoid further api calls if hosting cannot be found
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.controller.js
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/hosting.controller.js
Labels: enhancement, quality check ok

#810 fix(icon): domain icon
  client/app/components/sidebar-menu/sidebar-menu.config.js
Labels: bug, quality check ok

#809 fix(status-fix): fix status for cloud offers
  client/app/hosting/task/TASK.html
  client/app/hosting/task/hosting-task.controller.js
  client/app/hosting/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#818 fix(hosting.databases): update upgrade text
  client/app/hosting/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#820 fix(domains.create-website): api params
  client/app/website/configuration.controller.js
Labels: bug, quality check

#819 feat(hosting.logs): add support for GRA2
  client/app/hosting/user-logs/hosting-user-logs.controller.js
Labels: enhancement, quality check ok

#821 fix(tooltip-fix): disable tooltip for webhosting
  client/app/hosting/database/DATABASE_LIST.html
  client/app/hosting/database/hosting-database.controller.js
  client/app/hosting/hosting.controller.js
Labels: bug, quality check ok

#825 fix(sql_order): db order ram unit
  client/app/private-database/order/sql-database-order-controller.js
  client/app/private-database/order/sql-database-order.html
Labels: bug, quality check ok

#822 fix(hosting.web): blank page on ovhconfig error
  client/app/hosting/hosting.controller.js
  client/app/hosting/ovhconfig/hosting-ovhconfig.service.js
Labels: enhancement

#839 fix(navbar): rearrange help menu
  client/app/components/user/session.service.js
  client/app/core/translations/Messages_fr_FR.xml
Labels: bug, quality check, translation required

#851 refactor(babel): remove unused configuration and dependencies
  .babelrc
  package.json
  yarn.lock
Labels: enhancement
