Repository ovh-ux/ovh-manager-web, pull requests merged in 2018-03, with the labels that each got.

#328 hotfix(sidebar-menu): remove race condition when loading …
  client/app/components/sidebar-menu/sidebar-menu.config.js
Labels: bug, quality check

#330 chore(gulp): remove unmaintained and unused scripts
  Makefile
  gulp-scripts/babel.js
  gulp-scripts/copy.js
  gulp-scripts/dev.js
  gulp-scripts/jshint.js
  gulp-scripts/less.js
  gulp-scripts/ngAnnotate.js
  gulp-scripts/ngConstant.js
  gulp-scripts/template.js
  gulp-scripts/xml2json.js
  gulpfile.js
  package-lock.json
  package.json
Labels: enhancement

#329 chore(deps): bump ovh-ui-kit and ovh-ui-kit-bs
  package-lock.json
  package.json
Labels: bug, enhancement, ovh-ui-kit

#321 fix(email-domain): Fix for using deprecated API call
  client/app/email-domain/email-domain.popover.html
  client/app/email-domain/email-domain.service.js
  client/app/email-domain/email/account/email-domain-email-account.html
  client/app/email-domain/email/email-domain-email.controller.js
  client/app/email-domain/email/import-from-imap/email-domain-email-import-from-imap.controller.js
  client/app/email-domain/email/import-from-imap/email-domain-email-import-from-imap.html
  client/app/resources/i18n/email/Messages_cs_CZ.xml
  client/app/resources/i18n/email/Messages_de_DE.xml
  client/app/resources/i18n/email/Messages_en_ASIA.xml
  client/app/resources/i18n/email/Messages_en_AU.xml
  client/app/resources/i18n/email/Messages_en_CA.xml
  client/app/resources/i18n/email/Messages_en_GB.xml
  client/app/resources/i18n/email/Messages_en_SG.xml
  client/app/resources/i18n/email/Messages_en_US.xml
  client/app/resources/i18n/email/Messages_es_ES.xml
  client/app/resources/i18n/email/Messages_es_US.xml
  client/app/resources/i18n/email/Messages_fi_FI.xml
  client/app/resources/i18n/email/Messages_fr_CA.xml
  client/app/resources/i18n/email/Messages_fr_FR.xml
  client/app/resources/i18n/email/Messages_it_IT.xml
  client/app/resources/i18n/email/Messages_lt_LT.xml
  client/app/resources/i18n/email/Messages_nl_NL.xml
  client/app/resources/i18n/email/Messages_pl_PL.xml
  client/app/resources/i18n/email/Messages_pt_PT.xml
  constants.config.js
Labels: enhancement, quality check ok

#339 chore(*): bump dependencies version
  bower.json
  package-lock.json
  package.json
Labels: bug

#345 fix(translations): fix select typo
  client/app/resources/i18n/core/Messages_fr_FR.xml
  client/app/resources/i18n/domain/Messages_fr_FR.xml
  client/app/resources/i18n/hosting/Messages_fr_FR.xml
Labels: bug, quality check ok

#355 fix(privatedb): Add translation for correct version label display
  client/app/private-database/order/sql-database-order-controller.js
  client/app/private-database/order/sql-database-order.html
  client/app/resources/i18n/privateDatabase/Messages_fr_FR.xml
Labels: bug, quality check

#343 fix(email.accounts): link to import emails now works
  client/app/email-domain/email/account/email-domain-email-account.html
  client/app/email-domain/email/email-domain-email.controller.js
Labels: bug, quality check ok

#347 fix(email.delegate): Set property to display quota progress bar
  client/app/email-domain/delegate/email-domain-delegate.controller.js
Labels: bug, quality check

#346 fix(privatedb.metrics) : Use local format for time display
  client/app/private-database/metrics/private-database-metrics.constant.js
Labels: bug, quality check

#363 fix(email-domain): Remove old guides
  client/app/resources/i18n/core/Messages_fr_FR.xml
  constants.config.js
Labels: bug, quality check ok

#364 Chore/update ui kit
  package-lock.json
  package.json
Labels: enhancement, quality check ok

#350 fix(domains.alldom): remove alldoms domains from product domains list
  client/app/components/product/product.service.js
Labels: bug, quality check ok

#365 chore: updated CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#375 chore: bump version of ovh-ui-kit-bs
  bower.json
  client/app/css/source.less
Labels: enhancement, ovh-ui-kit

#370 Fix special characters display
  client/app/domain/domain-validator.service.js
  client/app/domain/glue/GLUE.html
  client/app/domain/glue/domain-glue.controller.js
Labels: bug, quality check ok

#354 Chore/generate changelog
  .scriptsrc
  CHANGELOG.md
  Gruntfile.js
  Makefile
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement

#369 Fix email-delegate : Set quota calculation method to static
  client/app/email-domain/delegate/email-domain-delegate.controller.js
Labels: bug, quality check ok
