Repository ovh-ux/ovh-manager-web, pull requests merged in 2018-02, with the labels that each got.

#278 Feature/oui datagrid hosting
  client/app/hosting/boost/BOOST.html
  client/app/hosting/boost/hosting-boost.controller.js
  client/app/hosting/database/dump/DUMPS.html
  client/app/hosting/database/dump/hosting-database-dump.controller.js
  client/app/hosting/database/hosting-database.service.js
  client/app/hosting/popover/user_logs.html
  client/app/hosting/task/TASK.html
  client/app/hosting/task/hosting-task.controller.js
  client/app/hosting/user-logs/USER_LOGS.html
  client/app/hosting/user-logs/hosting-user-logs.controller.js
Labels: enhancement, quality check ok

#301 fix(privateDatabase/order) : Update private database offers
  client/app/private-database/order/sql-database-order-controller.js
  client/app/private-database/order/tooltip/sql-database-order-dbaas.html
  client/app/private-database/order/tooltip/sql-database-order-premium.html
  client/app/resources/i18n/privateDatabase/Messages_fr_FR.xml
Labels: bug, quality check ok

#300 Add wizard for CAA resource record
  client/app/domain/domain-validator.service.js
  client/app/domain/zone/record/CAA/domain-zone-record-CAA.html
  client/app/domain/zone/record/add/domain-zone-record-add.html
  client/app/domain/zone/record/domain-zone-record.controller.js
  client/app/resources/i18n/domain/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#280 feat(navbar): update current navbar with new component oui-navbar
  Assets.js
  Gruntfile.js
  bower.json
  client/app/app.controller.js
  client/app/app.js
  client/app/components/manager-navbar/manager-navbar.module.js
  client/app/components/sidebar-menu/sidebar-menu.less
  client/app/components/user/session.controller.js
  client/app/components/user/session.service.js
  client/app/components/user/user.service.js
  client/app/css/less/common/global.less
  client/app/css/less/common/navbar.less
  client/app/css/source.less
  client/app/index.ejs
  client/app/resources/i18n/core/Messages_fr_FR.xml
  client/assets/images/navbar/icon-languages.svg
  client/assets/images/navbar/icon-languages_on.svg
  constants.config.js
  package-lock.json
  package.json
Labels: feature, quality check ok

#306 Feature/oui datagrid private db
  client/app/hosting/boost/BOOST.html
  client/app/hosting/database/dump/DUMPS.html
  client/app/hosting/user-logs/USER_LOGS.html
  client/app/hosting/user-logs/hosting-user-logs.controller.js
  client/app/private-database/database/archive/dump/private-database-database-archive-dump.controller.js
  client/app/private-database/database/archive/dump/private-database-database-archive-dump.html
  client/app/private-database/database/archive/list/private-database-database-archive-list.controller.js
  client/app/private-database/database/archive/list/private-database-database-archive-list.html
  client/app/private-database/database/dump/private-database-database-dump.controller.js
  client/app/private-database/database/dump/private-database-database-dump.html
  client/app/private-database/database/dump/private-database-database-dump.popover.html
  client/app/private-database/database/extension/private-database-database-extension.controller.js
  client/app/private-database/database/extension/private-database-database-extension.html
  client/app/private-database/database/popover/archive-list.html
  client/app/private-database/oom/private-database-oom.controller.js
  client/app/private-database/oom/private-database-oom.html
  client/app/private-database/user/list/private-database-user-list.controller.js
  client/app/private-database/user/list/private-database-user-list.html
  client/app/private-database/whitelist/add/private-database-whitelist-add.html
  client/app/private-database/whitelist/private-database-whitelist.controller.js
  client/app/private-database/whitelist/private-database-whitelist.html
  client/app/private-database/whitelist/private-database-whitelist.popover.html
  client/app/private-database/whitelist/private-database-whiteliste.service.js
  client/app/private-database/whitelist/update/private-database-whitelist-update.html
  client/app/resources/i18n/hosting/Messages_fr_FR.xml
  client/app/resources/i18n/privateDatabase/Messages_fr_FR.xml
Labels: ovh-ui-kit, quality check ok

#308 Feature/uu 625 (datagrid) Email
  client/app/email-domain/delegate/filter/email-domain-delegate-filter.controller.js
  client/app/email-domain/delegate/filter/email-domain-delegate-filter.html
  client/app/email-domain/delegate/filter/email-domain-delegate-filter.popover.html
  client/app/email-domain/email/filter/email-domain-email-filter.controller.js
  client/app/email-domain/email/filter/email-domain-email-filter.html
  client/app/email-domain/email/filter/email-domain-email-filter.popover.html
  client/app/email-domain/email/redirection/email-domain-email-redirection.controller.js
  client/app/email-domain/email/redirection/email-domain-email-redirection.html
  client/app/email-domain/email/redirection/email-domain-email-redirection.popover.html
  client/app/email-domain/task/email-domain-tab-task.controller.js
  client/app/email-domain/task/email-domain-task.html
Labels: ovh-ui-kit, quality check ok

#316 style(*): update layout responsive
  client/app/components/sidebar-menu/sidebar-menu.less
  client/app/index.ejs
Labels: bug

#318 fix(hosting cron): center spinner
  client/app/hosting/cron/CRON.html
Labels: enhancement

#317 fix(private database order): center spinner
  client/app/private-database/order/sql-database-order.html
Labels: enhancement

#319 fix(hosting module add): center spinner
  client/app/hosting/module/add/hosting-module-add.html
Labels: enhancement

#291 Fix/page email account migration
  client/app/email-domain/email-domain.popover.html
  client/app/email-domain/email-domain.service.js
  client/app/email-domain/email/account/email-domain-email-account.html
  client/app/email-domain/email/account/migrate/email-domain-email-account-migrate.controller.js
  client/app/email-domain/email/account/migrate/email-domain-email-account-migrate.html
  client/app/email-domain/email/email-domain-email.controller.js
  client/app/resources/i18n/email/Messages_fr_FR.xml
Labels: bug, quality check ok

#312 fix(domain.operations): button disabled properly
  client/app/domain-operation/domain-operation.html
Labels: bug, quality check ok

#315 feat(navbar): add hierarchical user menu
  bower.json
  client/app/components/user/session.controller.js
  client/app/components/user/session.service.js
  client/app/css/less/common/navbar.less
  client/app/index.ejs
  client/app/resources/i18n/core/Messages_fr_FR.xml
  package-lock.json
  package.json
Labels: enhancement, quality check ok, translation required
