Repository ovh-ux/ovh-manager-web, pull requests merged in 2018-05, with the labels that each got.

#397 fix: fix ssl order/regenerate button in multisite
  client/app/hosting/multisite/MULTISITE.html
  client/app/hosting/multisite/hosting-multisite.controller.js
  package-lock.json
Labels: bug, quality check

#391 Feat/dedicated exchange
  bower.json
  client/app/components/product/product.service.js
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/components/user/session.service.js
  package-lock.json
  package.json
  server/routes.js
Labels: enhancement, quality check ok

#392 Chore/email migration stepper
  bower.json
  client/app/app.js
  client/app/email-domain/email/account/migrate/email-domain-email-account-migrate.controller.js
  client/app/email-domain/email/account/migrate/email-domain-email-account-migrate.html
  client/app/resources/i18n/core/Messages_fr_FR.xml
  client/app/resources/i18n/email/Messages_cs_CZ.xml
  client/app/resources/i18n/email/Messages_de_DE.xml
  client/app/resources/i18n/email/Messages_en_ASIA.xml
  client/app/resources/i18n/email/Messages_en_AU.xml
  client/app/resources/i18n/email/Messages_en_CA.xml
  client/app/resources/i18n/email/Messages_en_GB.xml
  client/app/resources/i18n/email/Messages_en_SG.xml
  client/app/resources/i18n/email/Messages_en_US.xml
  client/app/resources/i18n/email/Messages_es_ES.xml
  client/app/resources/i18n/email/Messages_es_US.xml
  client/app/resources/i18n/email/Messages_fi_FI.xml
  client/app/resources/i18n/email/Messages_fr_CA.xml
  client/app/resources/i18n/email/Messages_fr_FR.xml
  client/app/resources/i18n/email/Messages_it_IT.xml
  client/app/resources/i18n/email/Messages_lt_LT.xml
  client/app/resources/i18n/email/Messages_nl_NL.xml
  client/app/resources/i18n/email/Messages_pl_PL.xml
  client/app/resources/i18n/email/Messages_pt_PT.xml
Labels: ovh-ui-kit, quality check ok, translation required

#401 Feat/cloud web
  client/app/components/tabs/tabs.html
  client/app/hosting/database/DATABASE_LIST.html
  client/app/hosting/database/dump/DUMPS.html
  client/app/hosting/database/dump/hosting-database-dump.controller.js
  client/app/hosting/database/private-activation/database-private-activation.html
  client/app/hosting/framework/FRAMEWORK.html
  client/app/hosting/framework/envvar/FRAMEWORK_ENVVARS.html
  client/app/hosting/framework/envvar/add/hosting-framework-envvar-add.controller.js
  client/app/hosting/framework/envvar/add/hosting-framework-envvar-add.html
  client/app/hosting/framework/envvar/delete/hosting-framework-envvar-delete.controller.js
  client/app/hosting/framework/envvar/delete/hosting-framework-envvar-delete.html
  client/app/hosting/framework/envvar/edit/hosting-framework-envvar-edit.controller.js
  client/app/hosting/framework/envvar/edit/hosting-framework-envvar-edit.html
  client/app/hosting/framework/envvar/hosting-framework-envvar.controller.js
  client/app/hosting/framework/envvar/hosting-framework-envvar.service.js
  client/app/hosting/framework/hosting-framework.controller.js
  client/app/hosting/framework/runtime/FRAMEWORK_RUNTIMES.html
  client/app/hosting/framework/runtime/add/hosting-framework-runtime-add.controller.js
  client/app/hosting/framework/runtime/add/hosting-framework-runtime-add.html
  client/app/hosting/framework/runtime/delete/hosting-framework-runtime-delete.controller.js
  client/app/hosting/framework/runtime/delete/hosting-framework-runtime-delete.html
  client/app/hosting/framework/runtime/edit/hosting-framework-runtime-edit.controller.js
  client/app/hosting/framework/runtime/edit/hosting-framework-runtime-edit.html
  client/app/hosting/framework/runtime/hosting-framework-runtime.controller.js
  client/app/hosting/framework/runtime/hosting-framework-runtime.service.js
  client/app/hosting/framework/runtime/set-default/hosting-framework-runtime-set-default.controller.js
  client/app/hosting/framework/runtime/set-default/hosting-framework-runtime-set-default.html
  client/app/hosting/ftp/FTP.html
  client/app/hosting/ftp/hosting-ftp.controller.js
  client/app/hosting/ftp/snapshot/generate/hosting-ftp-snapshot-generate.controller.js
  client/app/hosting/ftp/snapshot/generate/hosting-ftp-snapshot-generate.html
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/hosting-tabs.controller.js
  client/app/hosting/hosting.service.js
  client/app/hosting/multisite/MULTISITE.html
  client/app/hosting/multisite/add/hosting-multisite-add.controller.js
  client/app/hosting/multisite/add/hosting-multisite-add.html
  client/app/hosting/multisite/add/ovh/hosting-multisite-add-ovh.html
  client/app/hosting/multisite/hosting-multisite.controller.js
  client/app/hosting/multisite/hosting-multisite.service.js
  client/app/hosting/multisite/update/hosting-multisite-update.controller.js
  client/app/hosting/multisite/update/hosting-multisite-update.html
  client/app/hosting/offer/upgrade/hosting-offer-upgrade.html
  client/app/hosting/ovhconfig/hosting-ovhconfig.html
  client/app/hosting/statistics/STATISTICS.html
  client/app/private-database/database/add/private-database-database-add.html
  client/app/private-database/state/private-database-state.html
  client/app/resources/i18n/core/Messages_fr_FR.xml
  client/app/resources/i18n/hosting/Messages_fr_FR.xml
  package-lock.json
Labels: feature, quality check ok

#405 fix(navbar): remove labs URL
  constants.config.js
Labels: bug
