Repository ovh-ux/ovh-manager-web, pull requests merged in 2019-06, with the labels that each got.

#1097 fix(components.navbar): specify the right state for domain and hosting
  client/app/components/navbar/navbar.constants.js
  client/app/components/navbar/navbar.service.js
Labels: bug

#1102 fix(deps): upgrade ng-ovh-otrs to v7.1.3
  package.json
  yarn.lock
Labels: bug

#1106 fix(deps): upgrade ng-ovh-otrs to v7.1.4
  package.json
  yarn.lock
Labels: bug

#1105 fix(hosting): update translation related to ssl certificate
  client/app/hosting/translations/Messages_fr_FR.json
Labels: bug

#1107 trans(hosting.upgrade): add translations for cloudweb upgrade
  client/app/hosting/translations/Messages_fr_FR.json
Labels: bug

#1108 fix(domain.option): send only modification in payload
  client/app/domain/optin/optin.controller.js
Labels: bug

#1110 fix(deps): upgrade ovh-module-emailpro to v7.2.6
  package.json
  yarn.lock
Labels: bug

#1092 Feat/sidebar
  client/app/app.js
  client/app/components/ovh-angular-sidebar-menu/ovh-angular-sidebar-menu.module.js
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/components/sidebar-menu/sidebar-menu.less
  client/app/components/user/user-session.service.js
  client/app/components/webApp.controller.js
  client/app/css/less/common/global.less
  client/app/css/less/common/navbar.less
  client/app/css/source.less
  client/app/dns-zone/dns-zone.controller.js
  client/app/email-domain/email-domain.controller.js
  client/app/email-domain/email/responder/update/email-domain-email-responder-update.controller.js
  client/app/index.html
  client/app/index.js
  package.json
  webpack.config.js
  yarn.lock
Labels: enhancement, feature, quality check ok

#1114 Release v13.24.0
  client/app/app.js
  client/app/components/ovh-angular-sidebar-menu/ovh-angular-sidebar-menu.module.js
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/components/sidebar-menu/sidebar-menu.less
  client/app/components/user/user-session.service.js
  client/app/components/webApp.controller.js
  client/app/css/less/common/global.less
  client/app/css/less/common/navbar.less
  client/app/css/source.less
  client/app/dns-zone/dns-zone.controller.js
  client/app/email-domain/email-domain.controller.js
  client/app/email-domain/email/responder/update/email-domain-email-responder-update.controller.js
  client/app/index.html
  client/app/index.js
  package.json
  webpack.config.js
  yarn.lock
Labels: release :package:

#1117 fix(deps): upgrade ovh-module-emailpro to v7.2.7
  package.json
  yarn.lock
Labels: bug

#1112 build: bump @ovh-ux/manager-navbar
  package.json
  yarn.lock
Labels: dependencies

#1119 fix(deps): upgrade manager-server-sidebar to v0.2.1
  package.json
  yarn.lock
Labels: bug

#1118 Release v13.24.1
  package.json
  yarn.lock
Labels: release :package:

#1123 fix(deps): upgrade manager-server-sidebar to v0.2.2
  package.json
  yarn.lock
Labels: bug

#1131 fix(core): add missing clipboard component translations
  client/app/app.js
  client/app/core/translations/Messages_fr_FR.json
Labels: bug

#1132 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1129 Translation missing
  client/app/hosting/translations/Messages_fr_FR.json
Labels: bug, translation required

#1134 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: bug, dependencies

#1133 Release v13.24.3
  client/app/app.js
  client/app/core/translations/Messages_fr_FR.json
  client/app/hosting/translations/Messages_de_DE.json
  client/app/hosting/translations/Messages_en_ASIA.json
  client/app/hosting/translations/Messages_en_AU.json
  client/app/hosting/translations/Messages_en_CA.json
  client/app/hosting/translations/Messages_en_GB.json
  client/app/hosting/translations/Messages_en_SG.json
  client/app/hosting/translations/Messages_en_US.json
  client/app/hosting/translations/Messages_fi_FI.json
  client/app/hosting/translations/Messages_fr_FR.json
  client/app/hosting/translations/Messages_lt_LT.json
  client/app/hosting/translations/Messages_pt_PT.json
  package.json
  yarn.lock
Labels: release :package:

#1137 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1138 Release v13.24.4
  package.json
  yarn.lock
Labels: release :package:

#1142 fix(deps): upgrade ng-ovh-otrs to v7.1.5
  package.json
  yarn.lock
Labels: dependencies

#1130 fix(hosting.cdn.order): use the right offer code for CloudWeb
  client/app/hosting/cdn/order/hosting-cdn-order.controller.js
Labels: bug, quality check ok

#1144 build: bump @ovh-ux/manager-server-sidebar
  package.json
  yarn.lock
Labels: bug

#1127 fix(cloudweb): display fields for every language except php
  client/app/hosting/hosting.constant.js
  client/app/hosting/hosting.controller.js
  client/app/hosting/multisite/MULTISITE.html
  client/app/hosting/multisite/hosting-multisite.controller.js
  client/app/hosting/popover/multisite.html
  client/app/hosting/runtimes/add/hosting-runtimes-add.controller.js
  client/app/hosting/runtimes/add/hosting-runtimes-add.html
  client/app/hosting/runtimes/delete/hosting-runtimes-delete.controller.js
  client/app/hosting/runtimes/delete/hosting-runtimes-delete.html
  client/app/hosting/runtimes/edit/hosting-runtimes-edit.controller.js
  client/app/hosting/runtimes/edit/hosting-runtimes-edit.html
  client/app/hosting/runtimes/set-default/hosting-runtimes-set-default.controller.js
  client/app/hosting/runtimes/set-default/hosting-runtimes-set-default.html
Labels: bug, quality check ok

#1143 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies
