Repository ovh-ux/ovh-manager-web, pull requests merged in 2019-09, with the labels that each got.

#1230 Remove NL language
  package.json
  yarn.lock
Labels: quality check ok

#1234 fix: restore OTRS usage
  client/app/app.js
  client/app/config/constants.config.js
  client/app/index.html
  package.json
  yarn.lock
Labels: bug

#1235 feat: add manager banner
  client/app/app.js
  client/app/configuration/configuration.html
  package.json
  yarn.lock
Labels: quality check ok

#1204 Feat/dns order
  client/app/app.js
  client/app/app.routes.js
  client/app/config/constants.config.js
  client/app/domain/domain.routes.js
  client/app/domain/domain.service.js
  client/app/domain/translations/Messages_fr_FR.json
  client/app/domain/zone/ZONE.html
  client/app/domain/zone/activate/activate.component.js
  client/app/domain/zone/activate/activate.constants.js
  client/app/domain/zone/activate/activate.controller.js
  client/app/domain/zone/activate/activate.html
  client/app/domain/zone/activate/activate.module.js
  client/app/domain/zone/activate/activate.routing.js
  client/app/domain/zone/activate/domain-zone-activate.controller.js
  client/app/domain/zone/activate/domain-zone-activate.html
  client/app/domain/zone/activate/translations/Messages_fr_FR.json
  client/app/domain/zone/domain-zone-dns.controller.js
  client/app/domain/zone/domain-zone.state.js
  client/app/domain/zone/zone.module.js
  client/app/domain/zone/zone.routing.js
Labels: feature, quality check ok

#1240 fix(deps): upgrade some ovh modules
  package.json
  yarn.lock
Labels: bug, dependencies
