Repository ovh-ux/ovh-manager-web, pull requests merged in 2019-01, with the labels that each got.

#855 build(eslint): use eslint-formatter-pretty
  package.json
  yarn.lock
Labels: enhancement

#860 Feat/email pro mxplan
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/email-domain/email-domain.routes.js
  client/app/email-domain/order/email-domain-order.controller.js
  client/app/email-domain/order/email-domain-order.html
Labels: enhancement, quality check ok, translation required

#873 fix(emailpro): restore password update for emailpro
  package.json
  yarn.lock
Labels: bug

#841 Fix/welcome page for fr
  client/app/configuration/configuration.component.js
  client/app/configuration/configuration.controller.js
  client/app/configuration/configuration.html
  client/app/configuration/configuration.routes.js
  client/app/core/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#880 build(deps): upgrade web-universe-components to v1.2.0
  package.json
  yarn.lock
Labels: enhancement

#877 fix(delete-button): delete subscription button
  client/app/hosting/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#888 Upgrade ovh modules
  package.json
  yarn.lock
Labels: enhancement

#886 fix(domain): domain tabs tracking
  client/app/dns-zone/dns-zone-tabs.controller.js
  client/app/domain/domain-tabs.controller.js
Labels: enhancement, quality check ok

#893 fix(i18n): retrieve translations
  client/app/core/translations/Messages_it_IT.xml
  client/app/hosting/translations/Messages_es_ES.xml
  client/app/hosting/translations/Messages_it_IT.xml
  client/app/mailing-list/translations/Messages_fr_CA.xml
Labels: bug

#896 build(deps): upgrade web-universe-components to v1.2.2
  package.json
  yarn.lock
Labels: enhancement

#900 build(deps): upgrade ovh-module-exchange to v9.3.0
  package.json
  yarn.lock
Labels: enhancement
