Repository ovh-ux/ovh-manager-web, pull requests merged in 2019-05, with the labels that each got.

#1048 fix(i18n): retrieve translations
  client/app/domain/email-obfuscation/translations/Messages_pt_PT.xml
  client/app/domain/optin/translations/Messages_pt_PT.xml
  client/app/domain/translations/Messages_cs_CZ.xml
  client/app/domain/translations/Messages_de_DE.xml
  client/app/domain/translations/Messages_en_ASIA.xml
  client/app/domain/translations/Messages_en_AU.xml
  client/app/domain/translations/Messages_en_CA.xml
  client/app/domain/translations/Messages_en_GB.xml
  client/app/domain/translations/Messages_en_SG.xml
  client/app/domain/translations/Messages_en_US.xml
  client/app/domain/translations/Messages_es_ES.xml
  client/app/domain/translations/Messages_es_US.xml
  client/app/domain/translations/Messages_fi_FI.xml
  client/app/domain/translations/Messages_fr_CA.xml
  client/app/domain/translations/Messages_it_IT.xml
  client/app/domain/translations/Messages_lt_LT.xml
  client/app/domain/translations/Messages_nl_NL.xml
  client/app/domain/translations/Messages_pl_PL.xml
  client/app/domain/translations/Messages_pt_PT.xml
  client/app/domains/translations/Messages_pt_PT.xml
Labels: bug

#1032 fix(hosting): addition of certificate info in configuration tile
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.controller.js
Labels: enhancement, quality check ok

#1050 fix(domain-dashboard): fix ssl order button
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
Labels: bug, quality check ok

#1052 fix(deps): upgrade ovh-module-exchange to v9.4.3
  package.json
  yarn.lock
Labels: bug

#1058 fix(deps): upgrade ovh-module-* to the latest version
  package.json
  yarn.lock
Labels: bug

#1059 fix(i18n): retrieve translations
  client/app/core/translations/Messages_nl_NL.xml
  client/app/dns-zone/translations/Messages_nl_NL.xml
  client/app/domain/email-obfuscation/translations/Messages_nl_NL.xml
  client/app/domain/optin/translations/Messages_nl_NL.xml
  client/app/domain/translations/Messages_es_ES.xml
  client/app/domain/translations/Messages_nl_NL.xml
  client/app/domain/translations/Messages_pt_PT.xml
  client/app/hosting/translations/Messages_nl_NL.xml
Labels: bug

#1064 fix(private.database.ram.update): revert changes to display size in MB
  client/app/private-database/database/ram/update/private-database-database-ram-update.html
Labels: bug

#1068 fix(i18n): retrieve translations
  client/app/domain/translations/Messages_en_ASIA.xml
  client/app/domain/translations/Messages_en_AU.xml
  client/app/domain/translations/Messages_en_CA.xml
  client/app/domain/translations/Messages_en_GB.xml
  client/app/domain/translations/Messages_en_SG.xml
  client/app/domain/translations/Messages_en_US.xml
  client/app/domain/translations/Messages_it_IT.xml
  client/app/domain/translations/Messages_pl_PL.xml
Labels: bug

#1077 fix(i18n): retrieve translations
  client/app/domain/translations/Messages_de_DE.xml
Labels: bug

#1063 fix(modules-1-click): fix 1 click modules
  client/app/hosting/module/delete/hosting-module-delete.controller.js
  client/app/hosting/module/hosting-module.service.js
Labels: bug, quality check ok

#1078 build(deps): upgrade ovh-api-services to v6.18.1
  package.json
  yarn.lock
Labels: enhancement

#1085 fix(i18n): retrieve translations
  client/app/core/translations/Messages_pt_PT.xml
Labels: bug

#1086 build: bump manager-navbar to v0.5.0
  package.json
  yarn.lock
Labels: enhancement

#1091 fix(deps): upgrade ovh-module-* dependencies
  package.json
  yarn.lock
Labels: bug
