Repository ovh-ux/ovh-manager-web, pull requests merged in 2019-07, with the labels that each got.

#1069 feat(cloudweb): allow upgrading offer
  client/app/app.routes.js
  client/app/css/source.less
  client/app/email-domain/mailing-list/email-domain-mailing-list-tab-modules.controller.js
  client/app/email-domain/mailing-list/email-domain-mailing-list-view.html
  client/app/hosting/api-translator.service.js
  client/app/hosting/boost/BOOST.html
  client/app/hosting/boost/hosting-boost.controller.js
  client/app/hosting/cron/CRON.html
  client/app/hosting/cron/hosting-cron.controller.js
  client/app/hosting/database/DATABASE_LIST.html
  client/app/hosting/database/add/hosting-database-add.controller.js
  client/app/hosting/database/add/hosting-database-add.html
  client/app/hosting/database/hosting-database.controller.js
  client/app/hosting/ftp/FTP.html
  client/app/hosting/ftp/hosting-ftp.controller.js
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.controller.js
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/hosting.html
  client/app/hosting/hosting.routes.js
  client/app/hosting/hosting.service.js
  client/app/hosting/module/MODULE.html
  client/app/hosting/module/hosting-module.controller.js
  client/app/hosting/offer/upgrade/hosting-offer-upgrade.controller.js
  client/app/hosting/offer/upgrade/hosting-offer-upgrade.html
  client/app/hosting/translations/Messages_fr_FR.json
  client/app/index.js
  package.json
  yarn.lock
Labels: feature, quality check ok, translation required

#1150 Release v13.25.1
  client/app/core/translations/Messages_pt_PT.json
  client/app/email/translations/Messages_de_DE.json
  client/app/email/translations/Messages_en_ASIA.json
  client/app/email/translations/Messages_en_AU.json
  client/app/email/translations/Messages_en_CA.json
  client/app/email/translations/Messages_en_GB.json
  client/app/email/translations/Messages_en_SG.json
  client/app/email/translations/Messages_en_US.json
  client/app/email/translations/Messages_es_ES.json
  client/app/email/translations/Messages_fi_FI.json
  client/app/email/translations/Messages_it_IT.json
  client/app/email/translations/Messages_lt_LT.json
  client/app/hosting/translations/Messages_it_IT.json
  client/app/hosting/translations/Messages_pt_PT.json
Labels: release :package:

#1154 build(deps): upgrade ovh-api-services to v7.0.0
  package.json
  yarn.lock
Labels: dependencies

#1155 fix(deps): upgrade ovh-module-emailpro to v7.2.8
  package.json
  yarn.lock
Labels: bug, dependencies

#1157 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1158 build(deps): upgrade ng-ovh-otrs to v7.1.6
  package.json
  yarn.lock
Labels: bug, dependencies

#1161 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1156 Release v13.25.2
  client/app/email/translations/Messages_pt_PT.json
  client/app/hosting/cron/CRON.html
  client/app/hosting/cron/add-or-edit/hosting-cron-add-or-edit.controller.js
  client/app/hosting/cron/add-or-edit/hosting-cron-add-or-edit.html
  client/app/hosting/cron/delete/hosting-cron-delete.html
  client/app/hosting/cron/hosting-cron.constants.js
  client/app/hosting/cron/hosting-cron.controller.js
  client/app/hosting/cron/hosting-cron.service.js
  client/app/hosting/translations/Messages_de_DE.json
  client/app/hosting/translations/Messages_en_ASIA.json
  client/app/hosting/translations/Messages_en_AU.json
  client/app/hosting/translations/Messages_en_CA.json
  client/app/hosting/translations/Messages_en_GB.json
  client/app/hosting/translations/Messages_en_SG.json
  client/app/hosting/translations/Messages_en_US.json
  client/app/hosting/translations/Messages_es_ES.json
  client/app/hosting/translations/Messages_fi_FI.json
  client/app/hosting/translations/Messages_fr_FR.json
  client/app/hosting/translations/Messages_lt_LT.json
  package.json
  yarn.lock
Labels: release :package:

#1165 fix(deps): upgrade ovh-module-emailpro to v7.2.9
  package.json
  yarn.lock
Labels: bug

#1169 fix(deps): upgrade ovh-module-emailpro to ^7.2.10
  package.json
  yarn.lock
Labels: dependencies

#1173 fix(deps): upgrade ovh-module-emailpro to v7.1.8
  package.json
  yarn.lock
Labels: bug, quality check ok

#1177 fix(hosting.runtimes.add): ensure form validation
  client/app/hosting/runtimes/add/hosting-runtimes-add.controller.js
Labels: bug, quality check ok

#1180 build(deps): upgrade ovh-api-services to v8.0.0
  package.json
  yarn.lock
Labels: dependencies

#1181 build(deps): upgrade ng-ovh-http to v4.0.2
  package.json
  yarn.lock
Labels: dependencies

#1182 fix(anycast-dns): displayname punycode
  client/app/domain/anycast/domain-dns-anycast.controller.js
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
Labels: bug, quality check ok

#1183 build(deps): upgrade ng-ovh-web-universe-components to v4.0.3
  package.json
  yarn.lock
Labels: dependencies

#1184 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies
