Repository ovh-ux/ovh-manager-web, pull requests merged in 2019-04, with the labels that each got.

#965 feat(web-multiste): regenerate ssl
  client/app/hosting/multisite/MULTISITE.html
  client/app/hosting/multisite/hosting-multisite.controller.js
  client/app/hosting/multisite/hosting-multisite.service.js
  client/app/hosting/ssl/hosting-ssl.service.js
  client/app/hosting/translations/Messages_fr_FR.xml
  package.json
  yarn.lock
Labels: bug, quality check ok, translation required

#977 fix(hosting.web): logs url for GRA clusters
  client/app/hosting/hosting.controller.js
  yarn.lock
Labels: bug, quality check

#980 fix(domain.general-informations): display dashboard if invalid contact
  client/app/domain/general-informations/domain-general-informations.controller.js
Labels: bug, quality check ok

#984 feature(hosting.general.informations): use oui-clipboard
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
Labels: feature

#987 Increase max dynhost password length from 12 to 31
  client/app/domain/dynhost/login/add/domain-dynhost-login-add.controller.js
  client/app/domain/dynhost/login/edit/domain-dynhost-login-edit.controller.js
Labels: enhancement, quality check ok

#989 Update contributing
  CONTRIBUTING.md
Labels: enhancement

#991 fix(domain.general.informations): display domain offer for alldom pack
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
Labels: bug, quality check ok

#990 feat(domain.general.informations): add shortcut to manage alldom
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
  client/app/domain/general-informations/domain-general-informations.controller.js
Labels: feature, quality check ok

#1002 fix(i18n): retrieve translations
  client/app/hosting/translations/Messages_de_DE.xml
Labels: bug

#1000 fix(dns.order): use translation to show description
  client/app/dns-zone/dns-zone.routes.js
  client/app/dns-zone/new/dns-zone-new.html
  client/app/dns-zone/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#1003 translation for postgresql 11
  client/app/private-database/translations/Messages_fr_FR.xml
Labels: bug, translation required

#988 refactor(hosting.private.database.state): use oui-tile
  client/app/private-database/state/private-database-state.html
Labels: enhancement, quality check ok

#1004 fix(i18n.core): add chatbot menu entry
  client/app/core/translations/Messages_fr_FR.xml
Labels: bug

#1005 refactor(hosting.freedom): use oui-status oui-action-menu
  client/app/hosting/freedom/FREEDOM.html
Labels: enhancement

#996 fix(web-dashboard): replace service status component
  client/app/components/service-status/service-status-action.component.js
  client/app/components/service-status/service-status-action.constant.js
  client/app/components/service-status/service-status-action.controller.js
  client/app/components/service-status/service-status-action.html
  client/app/components/service-status/translations/Messages_cs_CZ.xml
  client/app/components/service-status/translations/Messages_de_DE.xml
  client/app/components/service-status/translations/Messages_en_ASIA.xml
  client/app/components/service-status/translations/Messages_en_AU.xml
  client/app/components/service-status/translations/Messages_en_CA.xml
  client/app/components/service-status/translations/Messages_en_GB.xml
  client/app/components/service-status/translations/Messages_en_SG.xml
  client/app/components/service-status/translations/Messages_en_US.xml
  client/app/components/service-status/translations/Messages_es_ES.xml
  client/app/components/service-status/translations/Messages_es_US.xml
  client/app/components/service-status/translations/Messages_fi_FI.xml
  client/app/components/service-status/translations/Messages_fr_CA.xml
  client/app/components/service-status/translations/Messages_fr_FR.xml
  client/app/components/service-status/translations/Messages_it_IT.xml
  client/app/components/service-status/translations/Messages_lt_LT.xml
  client/app/components/service-status/translations/Messages_nl_NL.xml
  client/app/components/service-status/translations/Messages_pl_PL.xml
  client/app/components/service-status/translations/Messages_pt_PT.xml
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  package.json
  yarn.lock
Labels: enhancement, quality check ok

#1008 fix(i18n): retrieve translations
  client/app/core/translations/Messages_cs_CZ.xml
  client/app/core/translations/Messages_de_DE.xml
  client/app/core/translations/Messages_en_ASIA.xml
  client/app/core/translations/Messages_en_AU.xml
  client/app/core/translations/Messages_en_CA.xml
  client/app/core/translations/Messages_en_GB.xml
  client/app/core/translations/Messages_en_SG.xml
  client/app/core/translations/Messages_en_US.xml
  client/app/core/translations/Messages_es_ES.xml
  client/app/core/translations/Messages_es_US.xml
  client/app/core/translations/Messages_fi_FI.xml
  client/app/core/translations/Messages_fr_CA.xml
  client/app/core/translations/Messages_it_IT.xml
  client/app/core/translations/Messages_lt_LT.xml
  client/app/core/translations/Messages_nl_NL.xml
  client/app/core/translations/Messages_pl_PL.xml
  client/app/core/translations/Messages_pt_PT.xml
  client/app/dns-zone/translations/Messages_cs_CZ.xml
  client/app/dns-zone/translations/Messages_de_DE.xml
  client/app/dns-zone/translations/Messages_en_ASIA.xml
  client/app/dns-zone/translations/Messages_en_AU.xml
  client/app/dns-zone/translations/Messages_en_CA.xml
  client/app/dns-zone/translations/Messages_en_GB.xml
  client/app/dns-zone/translations/Messages_en_SG.xml
  client/app/dns-zone/translations/Messages_en_US.xml
  client/app/dns-zone/translations/Messages_es_ES.xml
  client/app/dns-zone/translations/Messages_es_US.xml
  client/app/dns-zone/translations/Messages_fi_FI.xml
  client/app/dns-zone/translations/Messages_fr_CA.xml
  client/app/dns-zone/translations/Messages_it_IT.xml
  client/app/dns-zone/translations/Messages_lt_LT.xml
  client/app/dns-zone/translations/Messages_nl_NL.xml
  client/app/dns-zone/translations/Messages_pl_PL.xml
  client/app/dns-zone/translations/Messages_pt_PT.xml
  client/app/private-database/translations/Messages_cs_CZ.xml
  client/app/private-database/translations/Messages_de_DE.xml
  client/app/private-database/translations/Messages_en_ASIA.xml
  client/app/private-database/translations/Messages_en_AU.xml
  client/app/private-database/translations/Messages_en_CA.xml
  client/app/private-database/translations/Messages_en_GB.xml
  client/app/private-database/translations/Messages_en_SG.xml
  client/app/private-database/translations/Messages_en_US.xml
  client/app/private-database/translations/Messages_es_ES.xml
  client/app/private-database/translations/Messages_es_US.xml
  client/app/private-database/translations/Messages_fi_FI.xml
  client/app/private-database/translations/Messages_fr_CA.xml
  client/app/private-database/translations/Messages_it_IT.xml
  client/app/private-database/translations/Messages_lt_LT.xml
  client/app/private-database/translations/Messages_nl_NL.xml
  client/app/private-database/translations/Messages_pl_PL.xml
  client/app/private-database/translations/Messages_pt_PT.xml
Labels: bug

#997 feat(chatbot): open the chatbot from the assistance menu
  client/app/app.js
  client/app/components/user/session.service.js
  client/app/index.html
  package.json
  yarn.lock
Labels: feature, quality check ok

#1009 fix(i18n): retrieve translations
  client/app/core/translations/Messages_de_DE.xml
  client/app/core/translations/Messages_pt_PT.xml
  client/app/dns-zone/translations/Messages_de_DE.xml
  client/app/dns-zone/translations/Messages_pt_PT.xml
Labels: bug

#1012 fix(deps): upgrade @ovh-ux/ng-ovh-chatbot to v2.0.0
  package.json
  yarn.lock
Labels: bug

#1015 fix(domain-menu): fix domain menu and ticket link
  client/app/components/sidebar-menu/sidebar-menu.config.js
  client/app/components/user/session.service.js
Labels: bug, quality check ok

#1017 fix(i18n): retrieve translations
  client/app/core/translations/Messages_en_ASIA.xml
  client/app/core/translations/Messages_en_AU.xml
  client/app/core/translations/Messages_en_CA.xml
  client/app/core/translations/Messages_en_GB.xml
  client/app/core/translations/Messages_en_SG.xml
  client/app/core/translations/Messages_en_US.xml
  client/app/core/translations/Messages_pl_PL.xml
  client/app/dns-zone/translations/Messages_en_ASIA.xml
  client/app/dns-zone/translations/Messages_en_AU.xml
  client/app/dns-zone/translations/Messages_en_CA.xml
  client/app/dns-zone/translations/Messages_en_GB.xml
  client/app/dns-zone/translations/Messages_en_SG.xml
  client/app/dns-zone/translations/Messages_en_US.xml
  client/app/dns-zone/translations/Messages_pl_PL.xml
Labels: bug

#973 Feat/domain optin
  client/app/app.js
  client/app/domain/domain.constant.js
  client/app/domain/domain.controller.js
  client/app/domain/domain.routes.js
  client/app/domain/email-obfuscation/email-obfuscation.component.js
  client/app/domain/email-obfuscation/email-obfuscation.constant.js
  client/app/domain/email-obfuscation/email-obfuscation.controller.js
  client/app/domain/email-obfuscation/email-obfuscation.html
  client/app/domain/email-obfuscation/index.js
  client/app/domain/email-obfuscation/routes.js
  client/app/domain/email-obfuscation/translations/Messages_fr_FR.xml
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
  client/app/domain/general-informations/domain-general-informations.controller.js
  client/app/domain/optin/constants.js
  client/app/domain/optin/index.js
  client/app/domain/optin/optin.component.js
  client/app/domain/optin/optin.controller.js
  client/app/domain/optin/optin.html
  client/app/domain/optin/routes.js
  client/app/domain/optin/translations/Messages_fr_FR.xml
  client/app/domain/translations/Messages_fr_FR.xml
  client/app/domains/domains.controller.js
  client/app/domains/domains.html
  client/app/domains/owo/domains-owo.controller.js
  client/app/domains/owo/domains-owo.html
  client/app/domains/owo/domains-owo.service.js
  client/app/domains/translations/Messages_fr_FR.xml
  package.json
  yarn.lock
Labels: feature, quality check ok, translation required

#1022 fix(deps): upgrade ovh-module-emailpro to v7.2.3
  package.json
  yarn.lock
Labels: bug

#1019 fix(emails-export): export csv fix
  client/app/email-domain/email/account/export-csv/email-domain-email-account-export-csv.controller.js
Labels: bug, quality check ok

#1029 fix(domain): remove extra angular import statement
  client/app/domain/email-obfuscation/index.js
  client/app/domain/optin/index.js
Labels: bug

#1033 fix(domain.optin): fix redirect on optin submission
  client/app/domain/optin/optin.controller.js
Labels: bug, quality check ok

#1036 fix(domain.email-obfusctation): fix contact order
  client/app/domain/email-obfuscation/email-obfuscation.controller.js
Labels: bug

#1037 fix(domain.email-obfuscation): add missing word
  client/app/domain/email-obfuscation/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#1043 fix(domain): add missing translations
  client/app/domain/translations/Messages_fr_FR.xml
Labels: bug, quality check ok
