Repository ovh-ux/ovh-manager-web, pull requests merged in 2019-08, with the labels that each got.

#1185 Release v13.25.8
  client/app/domain/anycast/domain-dns-anycast.controller.js
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/translations/Messages_de_DE.json
  client/app/hosting/translations/Messages_en_ASIA.json
  client/app/hosting/translations/Messages_en_AU.json
  client/app/hosting/translations/Messages_en_CA.json
  client/app/hosting/translations/Messages_en_GB.json
  client/app/hosting/translations/Messages_en_SG.json
  client/app/hosting/translations/Messages_en_US.json
  client/app/hosting/translations/Messages_es_ES.json
  client/app/hosting/translations/Messages_fi_FI.json
  client/app/hosting/translations/Messages_it_IT.json
  client/app/hosting/translations/Messages_lt_LT.json
  client/app/hosting/translations/Messages_pl_PL.json
  client/app/hosting/translations/Messages_pt_PT.json
  package.json
  yarn.lock
Labels: release :package:

#1189 feat: add @ovh-ux/ng-ui-router-line-progress
  client/app/app.js
  client/app/css/source.less
  client/app/index.html
  package.json
  yarn.lock
Labels: feature

#1190 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1192 fix: update manager urls
  client/app/config/constants.config.js
Labels: bug

#1194 fix(layout): display skipnav translation correctly
  client/app/index.html
Labels: bug

#1196 feat: add @ovh-ux/ng-ovh-request-tagger
  package.json
  yarn.lock
Labels: enhancement

#1197 Release v13.27.0
  package.json
  yarn.lock
Labels: release :package:

#1186 fix(domain-options): addition of options tile
  client/app/domain/domain.constant.js
  client/app/domain/domain.service.js
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
  client/app/domain/general-informations/domain-general-informations.controller.js
  client/app/domain/options/delete/domain-options-delete.controller.js
  client/app/domain/options/delete/domain-options-delete.html
  client/app/domain/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required

#1200 Release v13.27.1
  client/app/domain/domain.constant.js
  client/app/domain/domain.service.js
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
  client/app/domain/general-informations/domain-general-informations.controller.js
  client/app/domain/options/delete/domain-options-delete.controller.js
  client/app/domain/options/delete/domain-options-delete.html
  client/app/domain/translations/Messages_fr_FR.json
Labels: release :package:

#1205 Release v13.27.2
  client/app/domain/translations/Messages_en_GB.json
  client/app/domain/translations/Messages_fi_FI.json
  client/app/domain/translations/Messages_fr_CA.json
  client/app/domain/translations/Messages_lt_LT.json
Labels: release :package:

#1210 docs: remove CODE_OF_CONDUCT.md file.
  CODE_OF_CONDUCT.md
Labels: documentation

#1214 Release v13.28.0
  client/app/app.js
  client/app/dns-zone/translations/Messages_es_ES.json
  client/app/domain/translations/Messages_de_DE.json
  client/app/domain/translations/Messages_es_ES.json
  client/app/domain/translations/Messages_it_IT.json
  client/app/domain/translations/Messages_pl_PL.json
  client/app/domain/translations/Messages_pt_PT.json
  package.json
  yarn.lock
Labels: release :package:

#1217 build(deps): upgrade ng-ovh-sso-auth to v4.2.0
  package.json
  yarn.lock
Labels: bug, dependencies

#1219 build(package.json): bump ng-ovh-sso-auth to v4.2.1
  package.json
  yarn.lock
Labels: dependencies

#1211 fix(ie11): remove duplicate dependency and bump urijs
  client/app/index.js
  package.json
  yarn.lock
Labels: bug, dependencies, quality check ok

#1223 fix(domain.dns): allow to order dns anycast
  client/app/domain/dns/DNS.html
Labels: bug, quality check ok

#1225 Release v13.28.2
  client/app/index.js
  package.json
  yarn.lock
Labels: release :package:
