Repository ovh-ux/ovh-manager-web, pull requests merged in 2019-03, with the labels that each got.

#944 fix(deps): upgrade ovh-module-exchange to v9.3.3
  package.json
  yarn.lock
Labels: enhancement

#936 Feat/restart single multisite
  client/app/hosting/multisite/MULTISITE.html
  client/app/hosting/multisite/hosting-multisite.controller.js
  client/app/hosting/multisite/hosting-multisite.service.js
  client/app/hosting/popover/multisite.html
  client/app/hosting/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#947 fix(deps): upgrade module emailpro and exchange
  package.json
  yarn.lock
Labels: enhancement

#948 fix(deps): upgrade module office and sharepoint
  package.json
  yarn.lock
Labels: enhancement

#943 build(deps): upgrade ng-ovh-swimming-poll to v4.0.0
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#952 fix(hosting.multisite): remove unnecessary catch blocks
  client/app/hosting/multisite/hosting-multisite.controller.js
Labels: bug, quality check ok

#946 build(deps): upgrade ng-ovh-api-wrappers
  client/app/app.js
  package.json
  yarn.lock
Labels: enhancement, quality check ok

#955 fix(deps): upgrade ng-at-internet to v4.0.0
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#956 Feat/mx plan
  client/app/components/user/session.service.js
  package.json
  yarn.lock
Labels: feature, quality check ok

#964 fix(deps): upgrade ovh-api-services to v6.1.2
  package.json
  yarn.lock
Labels: bug

#966 feat(domain): replace wuc-ovh-tabs with oui-header-tabs
  client/app/domain/dns/domain-dns.state.js
  client/app/domain/dnssec/domain-dnssec.state.js
  client/app/domain/domain-tabs.controller.js
  client/app/domain/domain.controller.js
  client/app/domain/domain.html
  client/app/domain/domain.routes.js
  client/app/domain/dynhost/domain-dynhost.state.js
  client/app/domain/general-informations/domain-general-informations.routes.js
  client/app/domain/general-informations/domain-general-informations.state.js
  client/app/domain/glue/domain-glue.state.js
  client/app/domain/redirection/domain-redirection.state.js
  client/app/domain/tasks/domain-tasks.state.js
  client/app/domain/zone/domain-zone.state.js
Labels: enhancement, quality check ok
