Repository ovh-ux/ovh-manager-web, pull requests merged in 2019-02, with the labels that each got.

#906 fix(domains-zone-edit): validation for cname record update
  client/app/domain/domain.service.js
Labels: bug, quality check ok

#910 fix(domains-zone-edit): cname conflict text
  client/app/domain/domain.service.js
  client/app/domain/translations/Messages_fr_FR.xml
  client/app/domain/zone/record/domain-zone-record.controller.js
  client/app/domain/zone/record/resume.html
Labels: bug, quality check ok, translation required

#913 fix(deps): upgrade emailpro, exchange and sharepoint modules
  package.json
  yarn.lock
Labels: bug

#915 fix(deps): upgrade ovh-module-sharepoint to v7.1.2
  package.json
  yarn.lock
Labels: bug

#897 fix(web-hosting): dashboard tile improvement
  client/app/components/service-status/service-status-action.component.js
  client/app/components/service-status/service-status-action.constant.js
  client/app/components/service-status/service-status-action.controller.js
  client/app/components/service-status/service-status-action.html
  client/app/components/service-status/translations/Messages_fr_FR.xml
  client/app/css/less/common/global.less
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.controller.js
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
  client/app/hosting/hosting-tabs.controller.js
  client/app/hosting/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#916 fix(web-hosting): tracking pages multiple times
  client/app/domain/domain-tabs.controller.js
  client/app/domain/domain.routes.js
Labels: bug, quality check ok

#919 fix(i18n): extract translations
  client/app/core/translations/Messages_fr_FR.xml
Labels: bug, translation required

#920 fix(deps): upgrade exchange module
  package.json
  yarn.lock
Labels: bug

#918 Feature/domain add plan tile
  client/app/components/service-status/service-status-action.html
  client/app/components/service-status/translations/Messages_fr_FR.xml
  client/app/domain/domain-tabs.controller.js
  client/app/domain/domain.routes.js
  client/app/domain/general-informations/GENERAL_INFORMATIONS.html
  client/app/domain/general-informations/domain-general-informations.controller.js
  client/app/domain/translations/Messages_fr_FR.xml
  client/app/hosting/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#895 feat(email): addition of plan tile
  client/app/email-domain/general-informations/email-domain-general-informations.controller.js
  client/app/email-domain/general-informations/email-domain-general-informations.html
  package.json
  yarn.lock
Labels: enhancement, quality check ok, translation required

#927 fix(deps): upgrade ovh-module-emailpro to v7.1.5
  package.json
  yarn.lock
Labels: bug

#933 fix(hosting): change main domain action availability
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.controller.js
  client/app/hosting/general-informations/GENERAL_INFORMATIONS.html
Labels: bug, quality check ok

#932 fix(deps): upgrade ng-ovh-apiv7 to v2.0.0
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#939 fix(deps): upgrade ovh-module-sharepoint to v7.1.3
  package.json
  yarn.lock
Labels: bug

#940 fix(deps): upgrade ovh-module-emailpro to v7.1.6
  package.json
  yarn.lock
Labels: bug

#937 fix(domain-zone): prevent multiple records getting added
  client/app/domain/zone/record/domain-zone-record.controller.js
Labels: bug, quality check ok

#926 fix(hosting-multisite): order and regenerate buttons visibility
  client/app/hosting/hosting.constant.js
  client/app/hosting/multisite/MULTISITE.html
  client/app/hosting/multisite/hosting-multisite.controller.js
  client/app/hosting/ssl/order/hosting-order-ssl.controller.js
  client/app/hosting/ssl/order/hosting-order-ssl.html
Labels: bug, quality check ok
